# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimproduct',
            old_name='material',
            new_name='material_id',
        ),
        migrations.RenameField(
            model_name='helperpdasfootwearvansavgfob',
            old_name='material',
            new_name='material_id',
        ),
        migrations.RenameField(
            model_name='helperpdasfootwearvansftyqt',
            old_name='material',
            new_name='material_id',
        ),
        migrations.RenameField(
            model_name='helperpdasfootwearvansprebuild',
            old_name='material',
            new_name='material_id',
        ),
        migrations.RenameField(
            model_name='helperpdasfootwearvansretailqt',
            old_name='material',
            new_name='material_id',
        ),
        migrations.AlterUniqueTogether(
            name='dimproduct',
            unique_together=set([('material_id', 'size')]),
        ),
        migrations.AlterUniqueTogether(
            name='helperpdasfootwearvansavgfob',
            unique_together=set([('factory_short_name', 'material_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='helperpdasfootwearvansftyqt',
            unique_together=set([('material_id', 'factory_short_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='helperpdasfootwearvansprebuild',
            unique_together=set([('region', 'material_id', 'size', 'factory_short_name', 'buying_program_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='helperpdasfootwearvansretailqt',
            unique_together=set([('region', 'sold_to_party', 'material_id', 'factory_short_name')]),
        ),
    ]
