# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdas', '0002_auto_20180512_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factdemandtotal',
            name='dim_date_buy_month',
        ),
        migrations.RemoveField(
            model_name='factdemandtotal',
            name='dim_factory_final',
        ),
        migrations.RemoveField(
            model_name='factdemandtotal',
            name='dim_factory_original_constrained',
        ),
        migrations.AddField(
            model_name='factdemandtotal',
            name='dim_date_id_buy_month',
            field=models.ForeignKey(db_column='dim_date_id_buy_month', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dim_date_id_buy_month', to='app_pdas.DimDate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factdemandtotal',
            name='dim_factory_id_final',
            field=models.ForeignKey(db_column='dim_factory_id_final', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dim_factory_id_final', to='app_pdas.DimFactory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factdemandtotal',
            name='dim_factory_id_original_constrained',
            field=models.ForeignKey(db_column='dim_factory_id_original_constrained', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dim_factory_id_original_constrained', to='app_pdas.DimFactory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factdemandtotal',
            name='dim_factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dim_factory_id', to='app_pdas.DimFactory'),
        ),
        migrations.AlterField(
            model_name='factdemandtotal',
            name='dim_factory_original_unconstrained',
            field=models.ForeignKey(db_column='dim_factory_original_unconstrained', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dim_factory_id_original_unconstrained', to='app_pdas.DimFactory'),
        ),
    ]
