# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdas', '0003_auto_20180512_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimproduct',
            old_name='material_emea',
            new_name='material_id_emea',
        ),
        migrations.RenameField(
            model_name='dimproduct',
            old_name='style',
            new_name='style_id',
        ),
        migrations.RenameField(
            model_name='dimproduct',
            old_name='style_erp',
            new_name='style_id_erp',
        ),
    ]
