# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdas', '0004_auto_20180513_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factdemandtotal',
            old_name='dim_factory_original_unconstrained',
            new_name='dim_factory_id_original_unconstrained',
        ),
    ]
