# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pdas', '0007_auto_20180514_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factprioritylist',
            old_name='dim_factory_2',
            new_name='dim_factory_id_2',
        ),
        migrations.RemoveField(
            model_name='factprioritylist',
            name='dim_factory_1',
        ),
        migrations.AddField(
            model_name='factprioritylist',
            name='dim_factory_id_1',
            field=models.ForeignKey(db_column='dim_factory_id_1', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_pdas.DimFactory'),
            preserve_default=False,
        ),
    ]
