# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 23:12
from __future__ import unicode_literals

import core.mixins_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimIAPFilterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_iapfilter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dms.DimIAPFilter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IAP Filter User',
            },
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.AlterUniqueTogether(
            name='dimiapfilteruser',
            unique_together=set([('dim_iapfilter', 'user')]),
        ),
    ]
