# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0002_auto_20180415_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='planbystore',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
