# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0004_auto_20180418_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategicsalesplan',
            old_name='avt',
            new_name='asp',
        ),
        migrations.AddField(
            model_name='strategicsalesplan',
            name='gross_sales_init',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
