# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0005_auto_20180423_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicsalesplan',
            name='average_cost_of_inventory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategicsalesplan',
            name='intake_beginning_of_season',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
