# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0006_auto_20180423_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurestoreinput',
            name='average_value_transaction',
            field=models.FloatField(blank=True, null=True, verbose_name='ASP'),
        ),
    ]
