# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0007_auto_20180523_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='planbymonthproductcategorystore',
            name='year_month_name_py',
            field=models.CharField(default=1, max_length=7, verbose_name='month PY'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='average_monthly_sales_for_ty',
            field=models.FloatField(blank=True, null=True, verbose_name='average monthly sales TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='average_value_transaction',
            field=models.FloatField(blank=True, null=True, verbose_name='ASP (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='net_retail_sales_in_eur_ty',
            field=models.FloatField(blank=True, null=True, verbose_name='net sales TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='relative_sales_volume_ty',
            field=models.FloatField(blank=True, null=True, verbose_name='relative sales TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='sales_accessories',
            field=models.FloatField(blank=True, null=True, verbose_name='net sales accessories TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='sales_adv_promotion',
            field=models.FloatField(blank=True, null=True, verbose_name='sales ADV promotion TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='sales_legwear',
            field=models.FloatField(blank=True, null=True, verbose_name='net sales legwear TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='sales_lingerie',
            field=models.FloatField(blank=True, null=True, verbose_name='net sales lingerie TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='sales_ready_to_wear',
            field=models.FloatField(blank=True, null=True, verbose_name='net sales ready-to-wear TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='featurestoreinput',
            name='sales_swimwear',
            field=models.FloatField(blank=True, null=True, verbose_name='net sales swimwear TY (EUR)'),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='asp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='average_cost_of_inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='beginning_season_inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='buying_budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='discounts',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='ending_season_inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='gmroi_percentage_target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='gross_margin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='gross_margin_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='gross_sales',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='gross_sales_index',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='gross_sales_init',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='gross_sales_per_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='intake_beginning_of_season',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='markdown',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='markup',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='net_sales',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='returns',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='sell_in',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategicsalesplan',
            name='sell_through_ratio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
