# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0010_auto_20180727_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_ly_essential_basic',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_ly_essential_fashion',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_ly_total',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_ly_trend_basic',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_ly_trend_fashion',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_py_carry_over',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_py_essential_basic',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_py_essential_fashion',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_py_total',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_py_trend_basic',
        ),
        migrations.RemoveField(
            model_name='rangearchitecture',
            name='range_effectiveness_py_trend_fashion',
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_ly_essential_basic',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level LY essential basic'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_ly_essential_fashion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level LY essential fashion'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_ly_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level LY total'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_ly_trend_basic',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level LY trend basic'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_ly_trend_fashion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level LY trend fashion'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_py_carry_over',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level PY carry over'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_py_essential_basic',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level PY essential basic'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_py_essential_fashion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level PY essential fashion'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_py_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level PY total'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_py_trend_basic',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level PY trend basic'),
        ),
        migrations.AddField(
            model_name='rangearchitecture',
            name='range_effectiveness_style_py_trend_fashion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='range effectiveness style level PY trend fashion'),
        ),
    ]
