# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-30 03:34
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0012_auto_20180727_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangePlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=150, verbose_name='product category')),
                ('product_division', models.CharField(max_length=150, verbose_name='product group')),
                ('product_essential_trend', models.CharField(blank=True, max_length=100, null=True, verbose_name='essential trend')),
                ('product_basic_fashion', models.CharField(blank=True, max_length=100, null=True, verbose_name='basic fashion')),
                ('range_width_style_py_rangearchitecture', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style codes from range architecture')),
                ('range_width_style_colour_py_rangearchitecture', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style-colour codes from range architecture')),
                ('range_width_style_py_rangemaster', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style codes from range master')),
                ('range_width_style_colour_py_rangemaster', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style-colour codes from range master')),
                ('dim_iapfilter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dms.DimIAPFilter')),
            ],
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.AlterUniqueTogether(
            name='rangeplan',
            unique_together=set([('dim_iapfilter', 'product_category', 'product_essential_trend', 'product_basic_fashion')]),
        ),
    ]
