# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-30 04:46
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0013_auto_20180730_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeAssortment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_user', models.CharField(max_length=2)),
                ('product_category', models.CharField(max_length=150, verbose_name='product category')),
                ('product_essential_trend', models.CharField(blank=True, max_length=100, null=True, verbose_name='essential trend')),
                ('product_basic_fashion', models.CharField(blank=True, max_length=100, null=True, verbose_name='basic fashion')),
                ('product_division', models.CharField(max_length=150, verbose_name='product group')),
                ('range_width_style_ly_storecluster', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style codes LY from store clustering')),
                ('range_width_style_colour_ly_storecluster', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style-colour codes LY from store clustering')),
                ('range_width_style_py', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style codes PY')),
                ('range_width_style_colour_py', models.IntegerField(blank=True, default=0, null=True, verbose_name='# of style-colour codes PY')),
                ('dim_iapfilter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dms.DimIAPFilter')),
            ],
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.AlterUniqueTogether(
            name='rangeassortment',
            unique_together=set([('dim_iapfilter', 'cluster_user', 'product_category', 'product_essential_trend', 'product_basic_fashion')]),
        ),
    ]
