# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0015_auto_20180801_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicsalesplan',
            name='sales_units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strategicsalesplan',
            name='sales_units_init',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
