# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0016_auto_20180808_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyplan',
            name='product_carryover',
        ),
        migrations.AddField(
            model_name='buyplan',
            name='cluster_user',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
