# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0017_auto_20180808_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyplan',
            name='cluster_user',
            field=models.CharField(max_length=2, verbose_name='cluster'),
        ),
        migrations.AlterField(
            model_name='buyplan',
            name='targeted_sell_thru',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='targeted sell thru %'),
        ),
        migrations.AlterField(
            model_name='rangeassortment',
            name='cluster_user',
            field=models.CharField(max_length=2, verbose_name='cluster'),
        ),
    ]
