# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0018_auto_20180808_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategicsalesplan',
            old_name='channel_mix',
            new_name='sales_year_mix',
        ),
        migrations.RemoveField(
            model_name='strategicsalesplan',
            name='seasonal_mix',
        ),
    ]
