# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 16:43
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0019_auto_20180810_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeCurve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=150, verbose_name='product category')),
                ('product_division', models.CharField(max_length=150, verbose_name='product group')),
                ('xs', models.FloatField(blank=True, default=0.1, null=True, verbose_name='size curve XS')),
                ('s', models.FloatField(blank=True, default=0.2, null=True, verbose_name='size curve S')),
                ('m', models.FloatField(blank=True, default=0.3, null=True, verbose_name='size curve M')),
                ('l', models.FloatField(blank=True, default=0.3, null=True, verbose_name='size curve L')),
                ('xl', models.FloatField(blank=True, default=0.1, null=True, verbose_name='size curve XL')),
                ('dim_iapfilter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dms.DimIAPFilter')),
            ],
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.AlterField(
            model_name='buyplan',
            name='size_curve_l',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='size curve L'),
        ),
        migrations.AlterField(
            model_name='buyplan',
            name='size_curve_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='size curve M'),
        ),
        migrations.AlterField(
            model_name='buyplan',
            name='size_curve_s',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='size curve S'),
        ),
        migrations.AlterField(
            model_name='buyplan',
            name='size_curve_xl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='size curve XL'),
        ),
        migrations.AlterField(
            model_name='buyplan',
            name='size_curve_xs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='size curve XS'),
        ),
        migrations.AlterUniqueTogether(
            name='sizecurve',
            unique_together=set([('dim_iapfilter', 'product_category')]),
        ),
    ]
