# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-26 04:06
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0020_auto_20180824_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTBPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=45)),
                ('product_division', models.CharField(max_length=150, verbose_name='product group')),
                ('net_sales_essential_fashion_py', models.IntegerField(default=0, verbose_name='net sales essential fashion')),
                ('mix_essential_fashion_py', models.FloatField(default=0, verbose_name='essential fashion mix PY')),
                ('mix_essential_fashion_ly', models.FloatField(default=0, verbose_name='essential fashion mix LY')),
                ('net_sales_trend_py', models.IntegerField(default=0, verbose_name='net sales trend')),
                ('mix_trend_py', models.FloatField(default=0, verbose_name='trend mix PY')),
                ('mix_trend_ly', models.FloatField(default=0, verbose_name='trend mix LY')),
                ('net_sales_essential_fashion_and_trend_py', models.IntegerField(default=0, verbose_name='net sales essential fashion and trend')),
                ('average_discount_rate', models.FloatField(default=0)),
                ('total_discount', models.IntegerField(default=0)),
                ('gross_sales_essential_fashion_and_trend_py', models.IntegerField(default=0, verbose_name='gross sales essential fashion and trend')),
                ('after_sale_sellthru_rate', models.FloatField(default=0)),
                ('before_sale_sellthru_rate', models.FloatField(default=0)),
                ('discount_in_sale_rate', models.FloatField(default=0)),
                ('sell_in_full_price', models.IntegerField(default=0)),
                ('insale_net_sales', models.IntegerField(default=0)),
                ('net_sales_sale', models.IntegerField(default=0)),
                ('discount_in_sale', models.IntegerField(default=0)),
                ('difference_in_discount', models.IntegerField(default=0)),
                ('end_of_season_inventory', models.IntegerField(default=0)),
                ('total_sell_in', models.IntegerField(default=0, verbose_name='total sell-in')),
                ('markup_rate', models.FloatField(default=0, verbose_name='mark-up rate')),
                ('total_buying_budget', models.IntegerField(default=0)),
                ('average_vat_percentage', models.FloatField(default=0, verbose_name='average VAT %')),
                ('total_buying_budget_adjusted_for_vat', models.IntegerField(default=0, verbose_name='total buying budget adjusted for VAT')),
                ('dim_iapfilter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dms.DimIAPFilter')),
            ],
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.AlterField(
            model_name='sizecurve',
            name='dim_iapfilter',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='app_dms.DimIAPFilter'),
        ),
        migrations.AlterUniqueTogether(
            name='buyplan',
            unique_together=set([('dim_iapfilter', 'cluster_user', 'product_category', 'product_style', 'product_essential_trend', 'product_basic_fashion')]),
        ),
        migrations.AlterUniqueTogether(
            name='otbplan',
            unique_together=set([('dim_iapfilter', 'region', 'product_division')]),
        ),
    ]
