# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 04:46
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0022_auto_20180826_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTBPlanMix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=45)),
                ('mix', models.FloatField(default=0)),
                ('dim_iapfilter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dms.DimIAPFilter')),
            ],
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.RemoveField(
            model_name='featurestoreinput',
            name='relative_sales_volume_ty',
        ),
        migrations.AlterUniqueTogether(
            name='otbplanmix',
            unique_together=set([('dim_iapfilter', 'region')]),
        ),
    ]
