# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dms', '0023_auto_20180828_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='otbplanmix',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
