# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 06:27
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Scenario',
            },
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.RenameField(
            model_name='factdemand',
            old_name='dim_date_logic_constrained',
            new_name='allocation_logic',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_date_allocation_constrained',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_date_allocation_final',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_date_allocation_overwritten',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_date_allocation_unconstrained',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_date_logic_final',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_date_logic_overwritten',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_date_logic_unconstrained',
        ),
        migrations.AddField(
            model_name='factdemand',
            name='dim_date_month_xf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimDate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factdemand',
            name='dim_scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimScenario'),
            preserve_default=False,
        ),
    ]
