# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dpp', '0002_auto_20180605_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimdate',
            old_name='month_name_accounting',
            new_name='month_name',
        ),
        migrations.RenameField(
            model_name='dimdate',
            old_name='month_name_short_accounting',
            new_name='month_name_short',
        ),
        migrations.RenameField(
            model_name='dimdate',
            old_name='year_accounting',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='dimdate',
            old_name='year_cw_accounting',
            new_name='year_cw',
        ),
        migrations.RenameField(
            model_name='dimdate',
            old_name='year_month_accounting',
            new_name='year_month',
        ),
    ]
