# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 06:06
from __future__ import unicode_literals

import core.mixins_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dpp', '0003_auto_20180606_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactDemandAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('allocation_logic', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity_user', models.IntegerField(default=0)),
                ('dim_date_month_xf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimDate')),
                ('dim_date_month_xf_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dim_date_month_xf_user', to='app_dpp.DimDate')),
                ('dim_demand_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimDemandCategory')),
                ('dim_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimProduct')),
                ('dim_production_line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimProductionLine')),
                ('dim_production_line_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dim_production_line_user', to='app_dpp.DimProductionLine')),
                ('dim_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimRelease')),
            ],
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='allocation_logic',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_production_line',
        ),
        migrations.RemoveField(
            model_name='factdemand',
            name='dim_scenario',
        ),
        migrations.AddField(
            model_name='dimscenario',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dimscenario',
            name='tree_dict',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factdemandallocation',
            name='dim_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimScenario'),
        ),
    ]
