# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dpp', '0004_auto_20180606_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('dim_construction_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimConstructionType')),
                ('dim_date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimDate')),
                ('dim_production_line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimProductionLine')),
                ('dim_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimRelease')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='factcapacity',
            unique_together=set([('dim_release', 'dim_production_line', 'dim_construction_type', 'dim_date')]),
        ),
    ]
