# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dpp', '0005_auto_20180607_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcapacity',
            name='dim_construction_type',
        ),
        migrations.AlterUniqueTogether(
            name='factcapacity',
            unique_together=set([('dim_release', 'dim_production_line', 'dim_date')]),
        ),
    ]
