# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dpp', '0006_auto_20180608_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperReleaseCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimRelease', verbose_name='release')),
            ],
            options={
                'verbose_name': 'Current Release',
            },
        ),
        migrations.AlterModelOptions(
            name='factcapacity',
            options={'verbose_name': 'Capacity'},
        ),
        migrations.AlterField(
            model_name='dimproductionline',
            name='dim_factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimFactory', verbose_name='plant code'),
        ),
        migrations.AlterField(
            model_name='factcapacity',
            name='dim_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimDate', verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='factcapacity',
            name='dim_production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimProductionLine', verbose_name='production line'),
        ),
        migrations.AlterField(
            model_name='factcapacity',
            name='dim_release',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_dpp.DimRelease'),
        ),
    ]
