# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dpp', '0007_auto_20180608_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factcapacity',
            old_name='dim_date',
            new_name='dim_date_month_xf',
        ),
        migrations.AlterUniqueTogether(
            name='factcapacity',
            unique_together=set([('dim_release', 'dim_production_line', 'dim_date_month_xf')]),
        ),
    ]
