# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 04:22
from __future__ import unicode_literals

import apps.projects.app_tattoo.models
import core.mixins_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('image_type', models.CharField(choices=[('thumbnail_80x80', 'thumbnail 80x80'), ('thumbnail_80x200', 'thumbnail 80x200')], max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('size', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Magic Convertion',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.projects.app_tattoo.models.upload_to_dump)),
                ('extension', models.CharField(max_length=10)),
                ('size', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_choice', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings',
            },
            bases=(models.Model, core.mixins_model.ModelFormFieldNames),
        ),
        migrations.AddField(
            model_name='convertimage',
            name='upload_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tattoo.UploadFile'),
        ),
    ]
