# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tattoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convertimage',
            options={'verbose_name': 'Magic Conversion'},
        ),
        migrations.RemoveField(
            model_name='convertimage',
            name='cluster',
        ),
    ]
